imports:
  - { resource: src/Infrastructure/services.yaml }
  - { resource: src/Transformer/services.yaml }
  - { resource: src/Service/services.yaml }

services:

  _defaults:
    public: false
    autowire: true