services:

  _defaults:
    public: false
    autowire: true

  FreshAdvance\ProductFeed\Transformer\ProductToArrayTransformerInterface:
    class: FreshAdvance\ProductFeed\Transformer\ProductToArrayTransformer
